name: Auto Comment
on: [issues, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v4.5
      - uses: bubkoo/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: >
            Hi @{{ author }}.

            Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.

            Please make sure you have given us as much context as possible.
          pullRequestOpened: >
            Hi @{{ author }}.

            Thank you for raising your pull request.

            Please make sure you have followed our contributing guidelines. We will review it as soon as possible.

            ## See your changes with

            ### [Documentation for development build](https://s3.cloud.cyfronet.pl/eosc-pl-common/pr-${{ steps.branch-name.outputs.current_branch }}/docs/index.html)
            
            ### Development build 

              ```html
              <script src="https://s3.cloud.cyfronet.pl/eosc-pl-common/pr-${{ steps.branch-name.outputs.current_branch }}/index.development.min.js"></script>
              <link rel="stylesheet" href="https://s3.cloud.cyfronet.pl/eosc-pl-common/pr-${{ steps.branch-name.outputs.current_branch }}/index.development.min.css" />
              ```

            ### Production build 

              ```html
              <script src="https://s3.cloud.cyfronet.pl/eosc-pl-common/pr-${{ steps.branch-name.outputs.current_branch }}/index.production.min.js"></script>
              <link rel="stylesheet" href="https://s3.cloud.cyfronet.pl/eosc-pl-common/pr-${{ steps.branch-name.outputs.current_branch }}/index.production.min.css" />
              ```
            
            ### Run commons locally with production build
            
            - copy paste beneath snippet to `index.html`
            
            - run `index.html` in a browser
            
            ```html
            
            <!DOCTYPE html>
            
            <html>
              <head>
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
              </head>
              <body>
                <eosc-common-main-header
                  username="name surname"
                  login-url="https://marketplace.eosc.pl/users/auth/checkin"
                  logout-url="https://marketplace.eosc.pl/users/logout"
                ></eosc-common-main-header>
                <EoscCommonTotopWrapper></EoscCommonTotopWrapper>
                <EoscCommonMainFooter></EoscCommonMainFooter>
                <script src="https://s3.cloud.cyfronet.pl/eosc-pl-common/pr-${{ steps.branch-name.outputs.current_branch }}/index.production.min.js"></script>
                <link rel="stylesheet" href="https://s3.cloud.cyfronet.pl/eosc-pl-common/pr-${{ steps.branch-name.outputs.current_branch }}/index.production.min.css" />
              </body>
            </html>
            
            ```
